[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "simulations"
version = "0.1.0"

[tool.poetry.dependencies]
joblib = "^1.2.0"
matplotlib = "^3.6.3"
numpy = "^1.24.1"
pandas = "^1.5.3"
python = ">=3.9,<3.11"
seaborn = "^0.12.2"
scipy = "1.8.0"
openpyxl = "^3.1.0"
