[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "simulations"
version = "0.1.0"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
numpy = "^1.24.1"
matplotlib = "^3.6.3"
pandas = "^1.5.3"
joblib = "^1.2.0"
seaborn = "^0.12.2"
